/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import json.JSONArray;
import json.JSONObject;
import model.bean.Veiculo;
import model.dao.VeiculoDAO;

/**
 *
 * @author Murilo
 */
public class ViewVeiculo extends javax.swing.JFrame {

    String modo;

    /**
     * Creates new form viewVeiculo
     */
    public ViewVeiculo() {
        initComponents();
        setLocationRelativeTo(null);
        iniciarJanelaVeiculo();
        modo = "Navegar";
        DefaultTableModel modelo = (DefaultTableModel) table_veiculo_veiculos.getModel();
        table_veiculo_veiculos.setRowSorter(new TableRowSorter(modelo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) table_veiculo_veiculos.getModel();
        modelo.setNumRows(0);
        VeiculoDAO pdao = new VeiculoDAO();

        for (Veiculo p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getMarca(),
                p.getModelo(),
                p.getPlaca(),
                p.getCor(),
                p.getAno()
            });

        }

    }

    public void manipulaInterfaceVeiculo() {
        switch (modo) {
            case "Navegar":
                botao_veiculo_salvar.setEnabled(false);
                botao_veiculo_cancelar.setEnabled(false);
                botao_veiculo_novo.setEnabled(true);
                botao_veiculo_editar.setEnabled(false);
                botao_veiculo_excluir.setEnabled(false);
                campo_veiculo_marca.setEnabled(false);
                campo_veiculo_modelo.setEnabled(false);
                campo_veiculo_placa.setEnabled(false);
                campo_veiculo_cor.setEnabled(false);
                campo_veiculo_ano.setEnabled(false);
                break;
            case "Novo":
                botao_veiculo_salvar.setEnabled(true);
                botao_veiculo_cancelar.setEnabled(true);
                botao_veiculo_novo.setEnabled(false);
                botao_veiculo_editar.setEnabled(false);
                botao_veiculo_excluir.setEnabled(false);
                campo_veiculo_marca.setEnabled(true);
                campo_veiculo_modelo.setEnabled(true);
                campo_veiculo_placa.setEnabled(true);
                campo_veiculo_cor.setEnabled(true);
                campo_veiculo_ano.setEnabled(true);
                break;
            case "Editar":
                botao_veiculo_salvar.setEnabled(true);
                botao_veiculo_cancelar.setEnabled(true);
                botao_veiculo_novo.setEnabled(false);
                botao_veiculo_editar.setEnabled(false);
                botao_veiculo_excluir.setEnabled(false);
                campo_veiculo_marca.setEnabled(true);
                campo_veiculo_modelo.setEnabled(true);
                campo_veiculo_placa.setEnabled(true);
                campo_veiculo_cor.setEnabled(true);
                campo_veiculo_ano.setEnabled(true);
                break;
            case "Excluir":
                botao_veiculo_salvar.setEnabled(false);
                botao_veiculo_cancelar.setEnabled(false);
                botao_veiculo_novo.setEnabled(true);
                botao_veiculo_editar.setEnabled(false);
                botao_veiculo_excluir.setEnabled(false);
                campo_veiculo_marca.setEnabled(false);
                campo_veiculo_modelo.setEnabled(false);
                campo_veiculo_placa.setEnabled(false);
                campo_veiculo_cor.setEnabled(false);
                campo_veiculo_ano.setEnabled(false);
                break;
            case "Selecao":
                botao_veiculo_salvar.setEnabled(false);
                botao_veiculo_cancelar.setEnabled(false);
                botao_veiculo_novo.setEnabled(true);
                botao_veiculo_editar.setEnabled(true);
                botao_veiculo_excluir.setEnabled(true);
                campo_veiculo_marca.setEnabled(false);
                campo_veiculo_modelo.setEnabled(false);
                campo_veiculo_placa.setEnabled(false);
                campo_veiculo_cor.setEnabled(false);
                campo_veiculo_ano.setEnabled(false);
                break;
            default:
                System.out.println("Modo inválido");
        }
    }

    public void iniciarJanelaVeiculo() {
        campo_veiculo_marca.setText("");
        campo_veiculo_modelo.setText("");
        campo_veiculo_placa.setText("");
        campo_veiculo_cor.setText("");
        campo_veiculo_ano.setText("");
        botao_veiculo_menu.setEnabled(true);
        botao_veiculo_importar.setEnabled(true);
        botao_veiculo_exportar.setEnabled(true);
    }

    public void gravarInformacaoVeiculo() {
        File file = new File("Veiculo.json");
        String conteudo;
        try {

            VeiculoDAO pdao = new VeiculoDAO();
            FileWriter f = new FileWriter(file, true);
            for (Veiculo p : pdao.read()) {
                JSONObject json = new JSONObject();
                conteudo = p.toJson().toString();
                conteudo += "\r\n";
                f.write(conteudo);
            }
            f.close();
            JOptionPane.showMessageDialog(null, "Dados Exportados com sucesso!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Não foi possível realizar esta ação");
        }
    }

    public void carregarInformacaoVeiculo() {
        try {
            VeiculoDAO pdao = new VeiculoDAO();
            FileReader fr = new FileReader("Veiculo.json");
            BufferedReader br = new BufferedReader(fr);

            String str;
            while ((str = br.readLine()) != null) {
                Veiculo p = new Veiculo();
                JSONArray json = new JSONArray(str.toString());
                for (int i = 0; i < json.length(); i++) {
                    JSONObject obj = json.getJSONObject(i);
                    p.setMarca(obj.getString("marca"));
                    p.setModelo(obj.getString("modelo"));
                    p.setPlaca(obj.getString("placa"));
                    p.setCor(obj.getString("cor"));
                    p.setAno(obj.getInt("ano"));
                    if (i + 1 == json.length()) {
                        pdao.create(p);
                    }
                }
            }
            br.close();
            JOptionPane.showMessageDialog(null, "Dados Importados com sucesso!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Não foi possível realizar esta ação");
        }
    }

    public void limparCamposVeiculo() {
        campo_veiculo_marca.setText("");
        campo_veiculo_modelo.setText("");
        campo_veiculo_placa.setText("");
        campo_veiculo_cor.setText("");
        campo_veiculo_ano.setText("");
    }

    public void lerTabelaPorMarca(String marca) {

        DefaultTableModel modelo = (DefaultTableModel) table_veiculo_veiculos.getModel();
        modelo.setNumRows(0);
        VeiculoDAO pdao = new VeiculoDAO();

        for (Veiculo p : pdao.lerPorMarca(marca)) {

            modelo.addRow(new Object[]{
                p.getMarca(),
                p.getModelo(),
                p.getPlaca(),
                p.getCor(),
                p.getAno()
            });

        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        campo_veiculo_marca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campo_veiculo_modelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campo_veiculo_placa = new javax.swing.JTextField();
        campo_veiculo_cor = new javax.swing.JTextField();
        campo_veiculo_ano = new javax.swing.JTextField();
        botao_veiculo_salvar = new javax.swing.JButton();
        botao_veiculo_cancelar = new javax.swing.JButton();
        botao_veiculo_menu = new javax.swing.JButton();
        botao_veiculo_exportar = new javax.swing.JButton();
        botao_veiculo_importar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_veiculo_veiculos = new javax.swing.JTable();
        botao_veiculo_editar = new javax.swing.JButton();
        botao_veiculo_novo = new javax.swing.JButton();
        botao_veiculo_excluir = new javax.swing.JButton();
        botao_veiculo_buscar = new javax.swing.JButton();
        campo_veiculo_buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(750, 260));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Marca:");

        campo_veiculo_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_veiculo_marcaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Modelo:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Placa:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Cor:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Ano:");

        campo_veiculo_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_veiculo_placaActionPerformed(evt);
            }
        });

        campo_veiculo_cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_veiculo_corActionPerformed(evt);
            }
        });

        botao_veiculo_salvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_veiculo_salvar.setText("Salvar");
        botao_veiculo_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_veiculo_salvarActionPerformed(evt);
            }
        });

        botao_veiculo_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_veiculo_cancelar.setText("Cancelar");
        botao_veiculo_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_veiculo_cancelarActionPerformed(evt);
            }
        });

        botao_veiculo_menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_veiculo_menu.setText("Menu principal");
        botao_veiculo_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_veiculo_menuActionPerformed(evt);
            }
        });

        botao_veiculo_exportar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_veiculo_exportar.setText("Exportar Dados");
        botao_veiculo_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_veiculo_exportarActionPerformed(evt);
            }
        });

        botao_veiculo_importar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_veiculo_importar.setText("Importar Dados");
        botao_veiculo_importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_veiculo_importarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_veiculo_ano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(campo_veiculo_placa)
                    .addComponent(campo_veiculo_modelo)
                    .addComponent(campo_veiculo_marca)
                    .addComponent(campo_veiculo_cor))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(botao_veiculo_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botao_veiculo_exportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao_veiculo_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botao_veiculo_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(botao_veiculo_importar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(82, 82, 82))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_veiculo_cancelar)
                            .addComponent(botao_veiculo_salvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(botao_veiculo_menu))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_veiculo_exportar)
                            .addComponent(botao_veiculo_importar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campo_veiculo_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_veiculo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campo_veiculo_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campo_veiculo_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(campo_veiculo_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_veiculo_veiculos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table_veiculo_veiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Marca", "Modelo", "Placa", "Cor", "Ano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_veiculo_veiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_veiculo_veiculosMouseClicked(evt);
            }
        });
        table_veiculo_veiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_veiculo_veiculosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table_veiculo_veiculos);

        botao_veiculo_editar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_veiculo_editar.setText("Editar");
        botao_veiculo_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_veiculo_editarActionPerformed(evt);
            }
        });

        botao_veiculo_novo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_veiculo_novo.setText("Novo");
        botao_veiculo_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_veiculo_novoActionPerformed(evt);
            }
        });

        botao_veiculo_excluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_veiculo_excluir.setText("Excluir");
        botao_veiculo_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_veiculo_excluirActionPerformed(evt);
            }
        });

        botao_veiculo_buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_veiculo_buscar.setText("Buscar por marca");
        botao_veiculo_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_veiculo_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botao_veiculo_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_veiculo_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_veiculo_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(campo_veiculo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(botao_veiculo_buscar)
                .addContainerGap())
            .addComponent(jScrollPane2)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_veiculo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botao_veiculo_novo)
                        .addComponent(botao_veiculo_editar)
                        .addComponent(botao_veiculo_excluir)
                        .addComponent(botao_veiculo_buscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_veiculo_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_veiculo_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_veiculo_marcaActionPerformed

    private void campo_veiculo_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_veiculo_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_veiculo_placaActionPerformed

    private void campo_veiculo_corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_veiculo_corActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_veiculo_corActionPerformed

    private void botao_veiculo_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_veiculo_salvarActionPerformed
        Veiculo p = new Veiculo();
        VeiculoDAO dao = new VeiculoDAO();
        p.setMarca(campo_veiculo_marca.getText());
        p.setModelo(campo_veiculo_modelo.getText());
        p.setPlaca(campo_veiculo_placa.getText());
        p.setCor(campo_veiculo_cor.getText());
        p.setAno(Integer.parseInt(campo_veiculo_ano.getText()));
        dao.create(p);

        limparCamposVeiculo();

        readJTable();

        modo = "Navegar";
        manipulaInterfaceVeiculo();
        limparCamposVeiculo();
    }//GEN-LAST:event_botao_veiculo_salvarActionPerformed

    private void botao_veiculo_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_veiculo_cancelarActionPerformed
        limparCamposVeiculo();
        modo = "Navegar";
        manipulaInterfaceVeiculo();
    }//GEN-LAST:event_botao_veiculo_cancelarActionPerformed

    private void table_veiculo_veiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_veiculo_veiculosMouseClicked
        if (table_veiculo_veiculos.getSelectedRow() != -1) {

            campo_veiculo_marca.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 0).toString());
            campo_veiculo_modelo.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 1).toString());
            campo_veiculo_placa.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 2).toString());
            campo_veiculo_cor.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 3).toString());
            campo_veiculo_ano.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_table_veiculo_veiculosMouseClicked

    private void botao_veiculo_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_veiculo_editarActionPerformed
        modo = "Editar";
        manipulaInterfaceVeiculo();

        if (table_veiculo_veiculos.getSelectedRow() != -1) {

            Veiculo p = new Veiculo();
            VeiculoDAO dao = new VeiculoDAO();
            p.setCor((String) table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 3));
            p.setModelo((String) table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 1));
            p.setMarca((String) table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 0));
            p.setAno((int) table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 4));
            p.setPlaca((String) table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 2));
            dao.update(p);
            limparCamposVeiculo();

            readJTable();

        }
    }//GEN-LAST:event_botao_veiculo_editarActionPerformed

    private void botao_veiculo_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_veiculo_novoActionPerformed
        limparCamposVeiculo();
        modo = "Novo";
        manipulaInterfaceVeiculo();
    }//GEN-LAST:event_botao_veiculo_novoActionPerformed

    private void botao_veiculo_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_veiculo_excluirActionPerformed
        if (table_veiculo_veiculos.getSelectedRow() != -1) {
            int index = table_veiculo_veiculos.getSelectedRow();
            Veiculo p = new Veiculo();
            VeiculoDAO dao = new VeiculoDAO();
            p.setPlaca((String) table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 2));
            dao.delete(p);

            limparCamposVeiculo();
            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
        modo = "Navegar";
    }//GEN-LAST:event_botao_veiculo_excluirActionPerformed

    private void table_veiculo_veiculosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_veiculo_veiculosKeyReleased
        if (table_veiculo_veiculos.getSelectedRow() != -1) {

            campo_veiculo_marca.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 0).toString());
            campo_veiculo_modelo.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 1).toString());
            campo_veiculo_placa.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 2).toString());
            campo_veiculo_cor.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 3).toString());
            campo_veiculo_ano.setText(table_veiculo_veiculos.getValueAt(table_veiculo_veiculos.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_table_veiculo_veiculosKeyReleased

    private void botao_veiculo_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_veiculo_buscarActionPerformed
        lerTabelaPorMarca(campo_veiculo_buscar.getText());
    }//GEN-LAST:event_botao_veiculo_buscarActionPerformed

    private void botao_veiculo_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_veiculo_menuActionPerformed
        new ViewHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_veiculo_menuActionPerformed

    private void botao_veiculo_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_veiculo_exportarActionPerformed
        gravarInformacaoVeiculo();
    }//GEN-LAST:event_botao_veiculo_exportarActionPerformed

    private void botao_veiculo_importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_veiculo_importarActionPerformed
        carregarInformacaoVeiculo();
    }//GEN-LAST:event_botao_veiculo_importarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_veiculo_buscar;
    private javax.swing.JButton botao_veiculo_cancelar;
    private javax.swing.JButton botao_veiculo_editar;
    private javax.swing.JButton botao_veiculo_excluir;
    private javax.swing.JButton botao_veiculo_exportar;
    private javax.swing.JButton botao_veiculo_importar;
    private javax.swing.JButton botao_veiculo_menu;
    private javax.swing.JButton botao_veiculo_novo;
    private javax.swing.JButton botao_veiculo_salvar;
    private javax.swing.JTextField campo_veiculo_ano;
    private javax.swing.JTextField campo_veiculo_buscar;
    private javax.swing.JTextField campo_veiculo_cor;
    private javax.swing.JTextField campo_veiculo_marca;
    private javax.swing.JTextField campo_veiculo_modelo;
    private javax.swing.JTextField campo_veiculo_placa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_veiculo_veiculos;
    // End of variables declaration//GEN-END:variables
}
