/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Murilo
 */
public class ViewHome extends javax.swing.JFrame {
    /**
     * Creates new form viewHome
     */
    public ViewHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botao_home_veiculos = new javax.swing.JButton();
        botao_home_clientes = new javax.swing.JButton();
        botao_home_locacoes = new javax.swing.JButton();
        botao_home_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Sistema de Locação de Veículos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Bem vindo!");

        botao_home_veiculos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao_home_veiculos.setText("Gerenciar veículos");
        botao_home_veiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_home_veiculosActionPerformed(evt);
            }
        });

        botao_home_clientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao_home_clientes.setText("Gerenciar Clientes");
        botao_home_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_home_clientesActionPerformed(evt);
            }
        });

        botao_home_locacoes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao_home_locacoes.setText("Gerenciar Locações");
        botao_home_locacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_home_locacoesActionPerformed(evt);
            }
        });

        botao_home_sair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao_home_sair.setText("Sair");
        botao_home_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_home_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botao_home_veiculos)
                .addGap(36, 36, 36)
                .addComponent(botao_home_clientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(botao_home_locacoes)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(botao_home_sair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_home_veiculos)
                    .addComponent(botao_home_clientes)
                    .addComponent(botao_home_locacoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(botao_home_sair)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_home_veiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_home_veiculosActionPerformed

        new ViewVeiculo().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_botao_home_veiculosActionPerformed

    private void botao_home_locacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_home_locacoesActionPerformed

        new ViewLocacao().setVisible(true);
        
            this.dispose();
    }//GEN-LAST:event_botao_home_locacoesActionPerformed

    private void botao_home_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_home_clientesActionPerformed

        new ViewCliente().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_botao_home_clientesActionPerformed

    private void botao_home_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_home_sairActionPerformed
    System.exit(0);
    }//GEN-LAST:event_botao_home_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_home_clientes;
    private javax.swing.JButton botao_home_locacoes;
    private javax.swing.JButton botao_home_sair;
    private javax.swing.JButton botao_home_veiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
