/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.dao.UserDAO;

/**
 *
 * @author Murilo
 */
public class ViewLoginDialog extends javax.swing.JDialog {
private String selected = "Portuguese";
    /**
     * Creates new form NewJDialog
     */
    public ViewLoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewlogin_username = new javax.swing.JLabel();
        field_login_login = new javax.swing.JTextField();
        viewlogin_password = new javax.swing.JLabel();
        field_login_password = new javax.swing.JPasswordField();
        button_login_enter = new javax.swing.JButton();
        viewlogin_language = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        viewlogin_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewlogin_username.setText("Nome de usuário");

        field_login_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        viewlogin_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewlogin_password.setText("Senha");

        field_login_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        field_login_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_login_passwordKeyPressed(evt);
            }
        });

        button_login_enter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_login_enter.setText("Entrar");
        button_login_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_login_enterActionPerformed(evt);
            }
        });

        viewlogin_language.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewlogin_language.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Portuguese", "English", "Spanish" }));
        viewlogin_language.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                viewlogin_languagePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        viewlogin_language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlogin_languageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(viewlogin_username)
                        .addComponent(field_login_login, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(viewlogin_password)
                        .addComponent(field_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_login_enter)
                .addGap(300, 300, 300))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewlogin_language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(viewlogin_language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(viewlogin_username)
                .addGap(18, 18, 18)
                .addComponent(field_login_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(viewlogin_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(button_login_enter)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_login_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_login_passwordKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_field_login_passwordKeyPressed

    private void button_login_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_login_enterActionPerformed

        UserDAO dao = new UserDAO();
        String password = new String(field_login_password.getPassword());

        if (dao.checkLogin(field_login_login.getText(), password)) {
            this.dispose();
            new ViewHome(selected).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Login and password entered do not match a user. Try again.");
        }
    }//GEN-LAST:event_button_login_enterActionPerformed

    private void viewlogin_languagePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_viewlogin_languagePopupMenuWillBecomeInvisible
        selected = viewlogin_language.getSelectedItem().toString();
        changeLanguage(selected);
    }//GEN-LAST:event_viewlogin_languagePopupMenuWillBecomeInvisible

    private void changeLanguage(String language) {
        switch (language) {
            case "Portuguese":
                viewlogin_username.setText("Nome de usuário");
                viewlogin_password.setText("Senha");
                button_login_enter.setText("Entrar");
                break;
            case "English":
                viewlogin_username.setText("Username");
                viewlogin_password.setText("Password");
                button_login_enter.setText("Log in");
                break;
            case "Spanish":
                viewlogin_username.setText("Nombre de usuario");
                viewlogin_password.setText("Contraseña");
                button_login_enter.setText("Iniciar sesión");
                break;
            default:
                viewlogin_username.setText("Nome de usuário");
                viewlogin_password.setText("Senha");
                button_login_enter.setText("Entrar");
        }
    }
    private void viewlogin_languageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlogin_languageActionPerformed

    }//GEN-LAST:event_viewlogin_languageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewLoginDialog dialog = new ViewLoginDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login_enter;
    private javax.swing.JTextField field_login_login;
    private javax.swing.JPasswordField field_login_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox viewlogin_language;
    private javax.swing.JLabel viewlogin_password;
    private javax.swing.JLabel viewlogin_username;
    // End of variables declaration//GEN-END:variables
}
