/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Date;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import json.JSONObject;
import model.bean.Cliente;
import model.bean.Locacao;
import model.bean.Veiculo;
import model.dao.ClienteDAO;
import model.dao.LocacaoDAO;
import model.dao.VeiculoDAO;
import xml.ConverteData;
import java.util.List;

/**
 *
 * @author Near
 */
public class ViewImport extends javax.swing.JFrame {

    String janela;

    /**
     * Creates new form ViewImport
     */
    public ViewImport(String janela) {
        this.janela = janela;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botao_import_txt = new javax.swing.JButton();
        botao_import_json = new javax.swing.JButton();
        botao_import_xml = new javax.swing.JButton();
        botao_import_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Selecione o formato a ser importado");

        botao_import_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_import_txt.setText("Txt");
        botao_import_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_import_txtActionPerformed(evt);
            }
        });

        botao_import_json.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_import_json.setText("Json");
        botao_import_json.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_import_jsonActionPerformed(evt);
            }
        });

        botao_import_xml.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_import_xml.setText("Xml");
        botao_import_xml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_import_xmlActionPerformed(evt);
            }
        });

        botao_import_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_import_cancelar.setText("Cancelar");
        botao_import_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_import_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_import_cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(botao_import_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_import_json, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(botao_import_xml, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_import_txt)
                    .addComponent(botao_import_json)
                    .addComponent(botao_import_xml))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(botao_import_cancelar)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_import_jsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_import_jsonActionPerformed
        switch (janela) {
            case "Veiculo":
                try {
                    VeiculoDAO pdao = new VeiculoDAO();
                    FileReader fr = new FileReader("Veiculo.json");
                    BufferedReader br = new BufferedReader(fr);
                    String str;
                    while ((str = br.readLine()) != null) {
                        Veiculo p = new Veiculo();
                        JSONObject json = new JSONObject(str);
                        p.setMarca(json.getString("marca"));
                        p.setModelo(json.getString("modelo"));
                        p.setPlaca(json.getString("placa"));
                        p.setCor(json.getString("cor"));
                        p.setAno(json.getInt("ano"));
                        pdao.create(p);
                    }
                    br.close();
                    JOptionPane.showMessageDialog(null, "Dados Importados com sucesso!");

                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar esta ação");
                }
                new ViewVeiculo().setVisible(true);
                this.dispose();
                break;
            case "Cliente":
                try {
                    DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                    java.sql.Date dataNascimento = null;
                    ClienteDAO pdao = new ClienteDAO();
                    FileReader fr = new FileReader("Cliente.json");
                    BufferedReader br = new BufferedReader(fr);
                    String str;
                    while ((str = br.readLine()) != null) {
                        String tempNascimento;
                        Cliente p = new Cliente();
                        JSONObject json = new JSONObject(str);
                        tempNascimento = json.getString("nascimento");
                        try {
                            dataNascimento = new java.sql.Date(fmt.parse(tempNascimento).getTime());
                        } catch (ParseException ex) {
                            Logger.getLogger(ViewImport.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        p.setNome(json.getString("nome"));
                        p.setCpf(json.getString("cpf"));
                        p.setRg(json.getString("rg"));
                        p.setNacionalidade(json.getString("nacionalidade"));
                        p.setTelefone(json.getString("telefone"));
                        p.setSexo(json.getString("sexo"));
                        p.setNascimento(dataNascimento);
                        pdao.create(p);
                    }
                    br.close();
                    JOptionPane.showMessageDialog(null, "Dados Importados com sucesso!");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar esta ação");
                }
                new ViewCliente().setVisible(true);
                this.dispose();
                break;
            case "Locacao":
                try {

                    // Formatar horarios
                    SimpleDateFormat formatador = new SimpleDateFormat("HH:mm");
                    DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                    java.util.Date hLoc = null;
                    java.util.Date hDev = null;
                    String locD, devD, locH, devH, cpfLocacao, placaLocacao;
                    int numeroLocacao;
                    java.sql.Date dataloc = null;
                    java.sql.Date datadev = null;
                    LocacaoDAO pdao = new LocacaoDAO();
                    FileReader fr = new FileReader("Locacao.json");
                    BufferedReader br = new BufferedReader(fr);

                    String str;
                    while ((str = br.readLine()) != null) {
                        Locacao p = new Locacao();
                        JSONObject json = new JSONObject(str);
                        cpfLocacao = json.getString("cpf_locacao");
                        placaLocacao = json.getString("placa_locacao");
                        numeroLocacao = json.getInt("numero_locacao");
                        locD = json.getString("data_locacao");
                        devD = json.getString("data_devolucao");
                        locH = json.getString("horario_locacao");
                        devH = json.getString("horario_devolucao");
                        try {
                            hLoc = formatador.parse(locH);
                            hDev = formatador.parse(devH);
                            dataloc = new java.sql.Date(fmt.parse(locD).getTime());
                            datadev = new java.sql.Date(fmt.parse(devD).getTime());
                        } catch (ParseException ex) {
                            Logger.getLogger(ViewImport.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        Time time1 = new Time(hLoc.getTime());
                        Time time2 = new Time(hDev.getTime());
                        p.setNumeroLocacao(numeroLocacao);
                        p.setCpfLocacao(cpfLocacao);
                        p.setPlacaLocacao(placaLocacao);
                        p.setDataLocacao(dataloc);
                        p.setDataDevolucao(datadev);
                        p.setHorarioLocacao(time1);
                        p.setHorarioDevolucao(time2);
                        pdao.create(p);
                    }
                    br.close();
                    JOptionPane.showMessageDialog(null, "Dados Importados com sucesso!");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar esta ação");
                }
                new ViewLocacao().setVisible(true);
                this.dispose();
                break;
            default:
                System.out.println("Janela inválida");
        }
        this.dispose();

    }//GEN-LAST:event_botao_import_jsonActionPerformed

    private void botao_import_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_import_txtActionPerformed
        SimpleDateFormat formatador = new SimpleDateFormat("HH:mm");
        DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        switch (janela) {
            case "Veiculo":
                String marca,
                 modelo,
                 placa,
                 cor;
                VeiculoDAO dao = new VeiculoDAO();
                int ano;
                try {
                    FileReader fr = new FileReader("Veiculo.txt");
                    BufferedReader br = new BufferedReader(fr);
                    String str;
                    while ((str = br.readLine()) != null) {
                        marca = str.substring(0, 100);
                        modelo = str.substring(100, 200);
                        placa = str.substring(200, 212);
                        cor = str.substring(212, 242);
                        ano = Integer.parseInt(str.substring(242, 246));
                        Veiculo p = new Veiculo();
                        p.setMarca(marca);
                        p.setModelo(modelo);
                        p.setPlaca(placa);
                        p.setCor(cor);
                        p.setAno(ano);
                        dao.create(p);
                    }
                    br.close();
                    JOptionPane.showMessageDialog(null, "Dados Importados com sucesso!");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar esta ação");
                }
                new ViewVeiculo().setVisible(true);
                this.dispose();
                break;
            case "Cliente":
                String nome,
                 cpf,
                 rg,
                 nacionalidade,
                 telefone,
                 sexo,
                 tempNascimento;
                java.sql.Date nascimento = null;
                ClienteDAO daoCliente = new ClienteDAO();
                try {
                    FileReader fr = new FileReader("Cliente.txt");
                    BufferedReader br = new BufferedReader(fr);
                    String str;
                    while ((str = br.readLine()) != null) {
                        nome = str.substring(0, 100);
                        cpf = str.substring(100, 114);
                        rg = str.substring(114, 126);
                        nacionalidade = str.substring(126, 156);
                        telefone = str.substring(156, 186);
                        sexo = str.substring(186, 216);
                        tempNascimento = str.substring(216, 226);
                        nascimento = new java.sql.Date(fmt.parse(tempNascimento).getTime());
                        Cliente p = new Cliente();
                        p.setNome(nome);
                        p.setCpf(cpf);
                        p.setRg(rg);
                        p.setNacionalidade(nacionalidade);
                        p.setTelefone(telefone);
                        p.setSexo(sexo);
                        p.setNascimento(nascimento);
                        daoCliente.create(p);
                    }
                    br.close();
                    JOptionPane.showMessageDialog(null, "Dados Importados com sucesso!");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar esta ação");
                } catch (ParseException ex) {
                    Logger.getLogger(ViewImport.class.getName()).log(Level.SEVERE, null, ex);
                }
                new ViewCliente().setVisible(true);
                this.dispose();
                break;
            case "Locacao":
                int numeroLocacao;
                String cpfLocacao,
                 placaLocacao,
                 tempDataLoc,
                 tempDataDev,
                 tempHoraLoc,
                 tempHoraDev;
                Date dataLocacao = null;
                Date dataDevolucao = null;
                java.util.Date horaLoc;
                java.util.Date horaDev;
                Time horaLocacao,
                 horaDevolucao;
                java.sql.Date dataLoc = null;
                java.sql.Date dataDev = null;
                LocacaoDAO daoLocacao = new LocacaoDAO();
                try {
                    FileReader fr = new FileReader("Locacao.txt");
                    BufferedReader br = new BufferedReader(fr);
                    String str;
                    while ((str = br.readLine()) != null) {
                        numeroLocacao = Integer.parseInt(str.substring(0, 4));
                        cpfLocacao = str.substring(4, 18);
                        placaLocacao = str.substring(18, 30);
                        tempDataLoc = str.substring(30, 40);
                        tempHoraLoc = str.substring(40, 45);
                        tempDataDev = str.substring(45, 55);
                        tempHoraDev = str.substring(55, 60);
                        dataLoc = new java.sql.Date(fmt.parse(tempDataLoc).getTime());
                        dataDev = new java.sql.Date(fmt.parse(tempDataDev).getTime());
                        dataLocacao = dataLoc;
                        dataDevolucao = dataDev;
                        horaLoc = formatador.parse(tempHoraLoc);
                        horaDev = formatador.parse(tempHoraDev);
                        horaLocacao = new Time(horaLoc.getTime());
                        horaDevolucao = new Time(horaDev.getTime());
                        Locacao p = new Locacao();
                        p.setNumeroLocacao(numeroLocacao);
                        p.setCpfLocacao(cpfLocacao);
                        p.setPlacaLocacao(placaLocacao);
                        p.setDataLocacao(dataLocacao);
                        p.setHorarioLocacao(horaLocacao);
                        p.setDataDevolucao(dataDevolucao);
                        p.setHorarioDevolucao(horaDevolucao);
                        daoLocacao.create(p);
                    }
                    br.close();
                    JOptionPane.showMessageDialog(null, "Dados Importados com sucesso!");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar esta ação");
                } catch (ParseException ex) {
                    Logger.getLogger(ViewImport.class.getName()).log(Level.SEVERE, null, ex);
                }
                new ViewLocacao().setVisible(true);
                this.dispose();
                break;
            default:
                System.out.println("Janela inválida");
        }
        this.dispose();
    }//GEN-LAST:event_botao_import_txtActionPerformed

    private void botao_import_xmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_import_xmlActionPerformed
        switch (janela) {
            case "Veiculo": {
                try {
                    List<Veiculo> lista = new ArrayList<>();
                    Veiculo teste = new Veiculo();
                    VeiculoDAO dao = new VeiculoDAO();
                    FileReader fr = new FileReader("veiculo.xml");
                    XStream xstream = new XStream(new DomDriver());
                    xstream.autodetectAnnotations(true);
                    xstream.registerConverter(new ConverteData());
                    lista = (List<Veiculo>) xstream.fromXML(fr);
                    dao.create(teste);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ViewImport.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            new ViewVeiculo().setVisible(true);
            this.dispose();
            break;
            case "Cliente":
                new ViewCliente().setVisible(true);
                this.dispose();
                break;
            case "Locacao":
                new ViewLocacao().setVisible(true);
                this.dispose();
                break;
            default:
                System.out.println("Janela inválida");
        }
        this.dispose();
    }//GEN-LAST:event_botao_import_xmlActionPerformed

    private void botao_import_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_import_cancelarActionPerformed
        switch (janela) {
            case "Veiculo":
                new ViewVeiculo().setVisible(true);
                this.dispose();
                break;
            case "Cliente":
                new ViewCliente().setVisible(true);
                this.dispose();
                break;
            case "Locacao":
                new ViewLocacao().setVisible(true);
                this.dispose();
                break;
            default:
                System.out.println("Janela inválida");
        }
    }//GEN-LAST:event_botao_import_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewImport("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_import_cancelar;
    private javax.swing.JButton botao_import_json;
    private javax.swing.JButton botao_import_txt;
    private javax.swing.JButton botao_import_xml;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
